data:
    name: 'coco'
    data_path: '/cluster/project/infk/cvg/students/junwang/datasets/cocos'
    seed: 42
    batch_size: 16
    test_batch_size: 16
    sizes:
        train: -1
        val: 500
        test: 1000
    img_size: [240, 320]
    photometric_augmentation:
        enable: true
        primitives: [
            'random_brightness', 'random_contrast', 'additive_speckle_noise',
            'additive_gaussian_noise', 'additive_shade', 'motion_blur']
        params:
            random_brightness: {brightness: 0.5}
            random_contrast: {strength_range: [0.5, 1.5]}
            additive_gaussian_noise: {stddev_range: [5, 95]}
            additive_speckle_noise: {prob_range: [0, 0.01]}
            additive_shade:
                transparency_range: [-0.8, 0.8]
                kernel_size_range: [100, 150]
            motion_blur: {max_kernel_size: 3}
    warped_pair:
        no_rot_proba: 0.5
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.3
            perspective_amplitude_y: 0.3
            patch_ratio: 0.85
            max_angle: 1.5
            n_angles: 100
            n_scales: 20
            allow_artifacts: true
        valid_border_margin: 3

model:
    pretrained_model: None

trainer:
    epochs: 25
    steps_per_epoch: 5000 # when batch_szie=16, it is 5174, 82784 images in total
    lr: 0.001
    milestones: [40000, 90000, 110000]
    lr_decay: 0.1
    save_period: 1


logging:
    dir: 'log/raft-lr-1e-3'
    step: 100



