data:
    seed: 42
    dir: '/cluster/project/infk/cvg/students/junwang/hypersim'
    image_size: (320, 240)
    batch_size: 8


model:
    pretrained_model: '/cluster/project/infk/cvg/students/junwang/HomoRAFT/log/raft-lr-1e-4_hard_no_mask/model_29_epoch.pth'

trainer:
    epochs: 25
    steps_per_epoch: 2500 # infinite
    lr: 0.0001
    milestones: [30000, 60000, 90000]
    lr_decay: 0.1
    save_period: 1
    loss: 'combined_loss'


logging:
    dir: 'log/hypersim-raft-lr-1e-4'
    step: 100



